# Generated by Django 3.0.8 on 2020-09-19 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16)),
                ('tournament_fee', models.FloatField()),
                ('amount', models.FloatField()),
                ('paid_date', models.DateField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('organizer', models.CharField(default='Ground ESports', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Pics')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('slots', models.IntegerField(default=100)),
                ('entry_fee', models.FloatField()),
                ('prize_pool', models.FloatField()),
                ('last_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=50)),
                ('team_tag', models.CharField(max_length=50)),
                ('team_number', models.CharField(max_length=15)),
                ('player1_ign', models.CharField(max_length=50)),
                ('player1_id', models.CharField(max_length=11)),
                ('player2_ign', models.CharField(max_length=50)),
                ('player2_id', models.CharField(max_length=11)),
                ('player3_ign', models.CharField(max_length=50)),
                ('player3_id', models.CharField(max_length=11)),
                ('player4_ign', models.CharField(max_length=50)),
                ('player4_id', models.CharField(max_length=11)),
                ('player5_ign', models.CharField(blank=True, max_length=50, null=True)),
                ('player5_id', models.CharField(blank=True, max_length=11, null=True)),
                ('payment_method', models.CharField(choices=[('HBL', 'Habib Bank Limited'), ('UBL', 'United Bank Limited'), ('MCB', 'Muslim Commerial Bank')], max_length=3)),
                ('registered', models.BooleanField(default=False)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Payment')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Tournament')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('message', models.TextField(max_length=500)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
